# Generated by Django 4.2.1 on 2023-06-08 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('register_id', models.TextField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('plate_number', models.TextField(max_length=20, unique=True)),
                ('registration_place', models.TextField()),
                ('registration_date', models.DateField()),
                ('purpose', models.CharField(choices=[('personal', 'Đi lại cá nhân'), ('passenger_service', 'Dịch vụ chở khách'), ('transportation_service', 'Dịch vụ vận tải')], default='personal', max_length=100)),
                ('type', models.TextField()),
                ('manufacturer', models.TextField()),
                ('model', models.TextField()),
                ('engine_number', models.TextField()),
                ('chassis_number', models.TextField()),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='owner.owner')),
            ],
        ),
    ]
