# Generated by Django 4.2.1 on 2023-06-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_rename_register_id_car_registration_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='registration_id',
            new_name='register_id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='inspection_status',
        ),
    ]
