# Generated by Django 4.2.1 on 2023-05-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.AlterField(
            model_name='car',
            name='registration_number',
            field=models.TextField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
