# Generated by Django 4.2.1 on 2023-05-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_car_id_alter_car_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='purpose',
            field=models.CharField(choices=[('personal', 'Đi lại cá nhân'), ('passenger_service', 'Dịch vụ chở khách'), ('transportation_service', 'Dịch vụ vận tải')], default='personal', max_length=100),
        ),
    ]
