# Generated by Django 4.2.1 on 2023-06-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_delete_inspection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='register_place',
            new_name='register_center',
        ),
        migrations.AddField(
            model_name='form',
            name='register_city',
            field=models.CharField(choices=[('89', 'An Giang'), ('77', 'Bà Rịa - Vũng Tàu'), ('24', 'Bắc Giang'), ('06', 'Bắc Kạn'), ('95', 'Bạc Liêu'), ('27', 'Bắc Ninh'), ('83', 'Bến Tre'), ('52', 'Bình Định'), ('74', 'Bình Dương'), ('70', 'Bình Phước'), ('60', 'Bình Thuận'), ('96', 'Cà Mau'), ('92', 'Cần Thơ'), ('04', 'Cao Bằng'), ('48', 'Đà Nẵng'), ('66', 'Đắk Lắk'), ('67', 'Đắk Nông'), ('11', 'Điện Biên'), ('75', 'Đồng Nai'), ('87', 'Đồng Tháp'), ('64', 'Gia Lai'), ('02', 'Hà Giang'), ('35', 'Hà Nam'), ('01', 'Hà Nội'), ('42', 'Hà Tĩnh'), ('30', 'Hải Dương'), ('31', 'Hải Phòng'), ('93', 'Hậu Giang'), ('79', 'Hồ Chí Minh'), ('17', 'Hoà Bình'), ('33', 'Hưng Yên'), ('56', 'Khánh Hòa'), ('91', 'Kiên Giang'), ('62', 'Kon Tum'), ('12', 'Lai Châu'), ('68', 'Lâm Đồng'), ('20', 'Lạng Sơn'), ('10', 'Lào Cai'), ('80', 'Long An'), ('36', 'Nam Định'), ('40', 'Nghệ An'), ('37', 'Ninh Bình'), ('58', 'Ninh Thuận'), ('25', 'Phú Thọ'), ('54', 'Phú Yên'), ('44', 'Quảng Bình'), ('49', 'Quảng Nam'), ('51', 'Quảng Ngãi'), ('22', 'Quảng Ninh'), ('45', 'Quảng Trị'), ('94', 'Sóc Trăng'), ('14', 'Sơn La'), ('72', 'Tây Ninh'), ('34', 'Thái Bình'), ('19', 'Thái Nguyên'), ('38', 'Thanh Hóa'), ('46', 'Thừa Thiên Huế'), ('82', 'Tiền Giang'), ('84', 'Trà Vinh'), ('08', 'Tuyên Quang'), ('86', 'Vĩnh Long'), ('26', 'Vĩnh Phúc'), ('15', 'Yên Bái')], default='01', max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='register_district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
